---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: neo-flask-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: "ubuntu-flask.coe332.tacc.cloud"
    http:
      paths:  
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: neo-flask-nodeport-service
            port:
              number: 5000
