apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo-redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: neo-redis-container
          image: redis:6.2
          volumeMounts:
            - name: neo-jackyyl-data
              mountPath: "/data"
          ports:
            - name: redis-port
              containerPort: 6379 
      volumes:
        - name: neo-jackyyl-data
          persistentVolumeClaim:
            claimName: neo-jackyyl-data

          