---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo-jackyyl-data
  namespace: jackyyl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cinder-csi
  resources:
    requests:
      storage: 10Gi