apiVersion: v1
kind: Service
metadata:
  name: flask-service-nodeport
spec:
  type: NodePort
  selector:
    app: neo-flask-app
  ports:
    - port: 80        
      targetPort: 5000 
      nodePort: 30001  