apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jackyyl-storageclass-access
subjects:
- kind: ServiceAccount
  name: jackyyl
  namespace: jackyyl
roleRef:
  kind: ClusterRole
  name: storageclass-reader
  apiGroup: rbac.authorization.k8s.io
